package entity;
// Generated 05-dic-2017 21:13:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer idGroup;
     private String name;
     private Set users = new HashSet(0);

    public Group() {
    }

    public Group(String name) {
       this.name = name;
    }
   
    public Integer getIdGroup() {
        return this.idGroup;
    }
    
    public void setIdGroup(Integer idGroup) {
        this.idGroup = idGroup;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getUsers() {
        return users;
    }

    public void setUsers(Set users) {
        this.users = users;
    }




}


