package entity;
// Generated 05-dic-2017 21:13:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private String email;
     private String firstname;
     private String lastname;
     private Integer type;
     private Set exercises = new HashSet(0);
     private Set groups = new HashSet(0);

    public User() {
    }

    public User(String username, String password, String email, String firstname, String lastname, Integer type, Set exercises, Set groups) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.firstname = firstname;
       this.lastname = lastname;
       this.type = type;
       this.exercises = exercises;
       this.groups = groups;
    }
    
    public User(String username, String password, String email, String firstname, String lastname, Integer type, Set exercises) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.firstname = firstname;
       this.lastname = lastname;
       this.type = type;
       this.exercises = exercises;
    }
    
    public User(String username, String password, String email, String firstname, String lastname, Set groups, Integer type) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.firstname = firstname;
       this.lastname = lastname;
       this.type = type;
       this.groups = groups;
    }
    
    public User(String username, String password, String email, String firstname, String lastname, Integer type) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.firstname = firstname;
       this.lastname = lastname;
       this.type = type;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }

    public Set getExercises() {
        return exercises;
    }

    public void setExercises(Set exercises) {
        this.exercises = exercises;
    }

    public Set getGroups() {
        return groups;
    }

    public void setGroups(Set groups) {
        this.groups = groups;
    }




}


